import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import './styles.css'
import { clientRuntime } from './foundation/runtime'
import { cacheResponse, flushMutations, queueMutation, readCachedResponse } from './offline/offline-store'

if ('serviceWorker' in navigator) window.addEventListener('load', () => { void navigator.serviceWorker.register('/sw.js') })

type Screen = 'dashboard' | 'transfers' | 'settlements' | 'accounts' | 'people' | 'reports' | 'settings'
type IconName = 'home' | 'transfer' | 'settle' | 'account' | 'people' | 'report' | 'settings' | 'search' | 'bell' | 'plus' | 'arrow' | 'more' | 'filter' | 'chevron' | 'check' | 'menu' | 'close' | 'building' | 'printer'

const navItems: { id: Screen; label: string; icon: IconName }[] = [
  { id: 'dashboard', label: 'الرئيسية', icon: 'home' }, { id: 'transfers', label: 'الحوالات', icon: 'transfer' },
  { id: 'settlements', label: 'التسويات', icon: 'settle' }, { id: 'accounts', label: 'الحسابات', icon: 'account' },
  { id: 'people', label: 'الأشخاص', icon: 'people' }, { id: 'reports', label: 'التقارير', icon: 'report' }, { id: 'settings', label: 'الإعدادات', icon: 'settings' },
]

function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const common = { width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.7, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const }
  const paths: Partial<Record<IconName, ReactNode>> = {
    home: <><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9M9 20v-6h6v6"/></>, transfer: <><path d="M4 7h14"/><path d="m14 3 4 4-4 4"/><path d="M20 17H6"/><path d="m10 13-4 4 4 4"/></>, settle: <><circle cx="12" cy="12" r="8.5"/><path d="M8 12h8M12 8v8"/></>, account: <><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-3.1 3.1-4.7 7-4.7s6.2 1.6 7 4.7"/></>, people: <><circle cx="9" cy="8" r="3"/><path d="M3 20c.5-3.2 2.5-5 6-5s5.5 1.8 6 5"/><path d="M16 5.5a3 3 0 0 1 0 5.8M17 15.2c2.4.5 3.7 2.1 4 4.8"/></>, report: <><path d="M5 20V10M12 20V4M19 20v-7"/><path d="M3 20h18"/></>, settings: <><path d="M12 15.2a3.2 3.2 0 1 0 0-6.4 3.2 3.2 0 0 0 0 6.4Z"/><path d="m19.4 15 .1.1a1.7 1.7 0 0 1-2.4 2.4l-.1-.1a1.7 1.7 0 0 0-2.9 1.2v.2a1.7 1.7 0 0 1-3.4 0v-.2a1.7 1.7 0 0 0-2.9-1.2l-.1.1a1.7 1.7 0 0 1-2.4-2.4l.1-.1A1.7 1.7 0 0 0 6.2 12a1.7 1.7 0 0 1 0-3.4h.2a1.7 1.7 0 0 0 1.2-2.9l-.1-.1A1.7 1.7 0 1 1 9.9 3.2l.1.1A1.7 1.7 0 0 0 12.9 2h.2a1.7 1.7 0 0 1 3.4 0v.2a1.7 1.7 0 0 0 2.9 1.2l.1-.1a1.7 1.7 0 0 1 2.4 2.4l-.1.1A1.7 1.7 0 0 0 20.6 9v.2a1.7 1.7 0 0 1 0 3.4h-.2a1.7 1.7 0 0 0-1 2.4Z"/></>, search: <><circle cx="10.8" cy="10.8" r="6.5"/><path d="m16 16 5 5"/></>, bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 22h4"/></>, plus: <><path d="M12 5v14M5 12h14"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, more: <><circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/></>, filter: <><path d="M4 6h16M7 12h10M10 18h4"/></>, chevron: <path d="m8 10 4 4 4-4"/>, check: <path d="m5 12 4 4L19 6"/>, menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, building: <><path d="M4 21V5l8-3 8 3v16M2 21h20M8 8h1M15 8h1M8 12h1M15 12h1M8 16h1M15 16h1"/></>,
  }
  if (name === 'printer') return <svg {...common}><path d="M6 9V3h12v6"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 14h12v7H6z"/></svg>
  return <svg {...common}>{paths[name]}</svg>
}

function GlassCard({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`glass-card ${className}`}>{children}</div> }
function GlassButton({ children, primary = false, onClick, className = '', type = 'button' }: { children: ReactNode; primary?: boolean; onClick?: () => void; className?: string; type?: 'button' | 'submit' }) { return <button type={type} className={`glass-button ${primary ? 'primary' : ''} ${className}`} onClick={onClick}>{children}</button> }

type ApiUser = { id: string; username: string; role: 'ADMIN' | 'VIEWER' }
type ApiTransfer = { id: string; businessNumber: string; direction: 'SENT' | 'RECEIVED'; currency: string; total: string; amount?: string; commission?: string; date: string; senderName?: string; recipientName?: string | null; beneficiaryName?: string | null; beneficiaryPhone?: string | null; beneficiaryCountry?: string | null; location?: string | null; notes?: string | null; party: { id: string; name: string } }
type ApiParty = { id: string; type: 'PERSON' | 'OFFICE' | 'COMPANY'; name: string; phone?: string | null; address?: string | null; country?: string | null; notes?: string | null; ownerName?: string | null; responsibleName?: string | null }
type ApiSettlement = { id: string; businessNumber: string; direction: 'WE_PAID_THEM' | 'THEY_PAID_US'; currency: string; amount: string; date: string; party: { name: string } }
type ApiOpeningBalance = { id: string; partyId: string; currency: string; direction: 'WE_ARE_OWED' | 'THEY_ARE_OWED'; amount: string; party: { name: string } }
type UiTransfer = { no: string; person: string; type: string; currency: string; amount: string; status: string; date: string }
type DashboardData = { transferCount: number; settlementCount: number; balances: Array<{ currency: string; weAreOwed: string; theyAreOwed: string }>; byCurrency: Array<{ currency: string; commission: string }> }
class ApiResponseError extends Error {}

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const method = init?.method ?? 'GET'
  try {
    const response = await fetch(`${clientRuntime.apiBaseUrl}${path}`, { ...init, credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) } })
    if (!response.ok) throw new ApiResponseError(response.status === 401 ? 'AUTH_REQUIRED' : (await response.json().catch(() => null))?.error ?? 'تعذر الاتصال بالخادم.')
    if (response.status === 204) return undefined as T
    const value = await response.json() as T
    if (method === 'GET' && !path.startsWith('/auth/')) void cacheResponse(path, value)
    return value
  } catch (error) {
    if (method !== 'GET' && !(error instanceof ApiResponseError)) { await queueMutation(path, method, typeof init?.body === 'string' ? init.body : undefined); return {} as T }
    if (!path.startsWith('/auth/')) { const cached = await readCachedResponse<T>(path); if (cached !== null) return cached }
    throw error
  }
}

function toUiTransfer(transfer: ApiTransfer): UiTransfer {
  return { no: transfer.businessNumber, person: transfer.party.name, type: transfer.direction === 'SENT' ? 'إرسال حوالة' : 'استلام حوالة', currency: transfer.currency, amount: transfer.total, status: 'مكتملة', date: new Date(transfer.date).toLocaleDateString('ar-IQ') }
}

function escapePrint(value: unknown): string { return String(value ?? '—').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;') }
async function printTransfer(id: string, printWindow: Window) {
  try {
    const transfer = await api<ApiTransfer>(`/transfers/${id}`)
    const date = new Date(transfer.date).toLocaleDateString('ar-IQ')
    printWindow.document.open()
    printWindow.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${escapePrint(transfer.businessNumber)}</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font-family:Arial,Tahoma,sans-serif;color:#18211f;margin:0}header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #075c50;padding-bottom:18px;margin-bottom:28px}h1{font-size:26px;margin:0 0 8px;color:#075c50}h2{font-size:18px;margin:0 0 16px}.brand{text-align:left}.brand strong{display:block;font-size:22px}.brand span{font-size:12px;color:#61716c}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px;background:#f2f6f4;padding:18px;border-radius:10px;margin-bottom:24px}.meta div{display:flex;justify-content:space-between;border-bottom:1px solid #d9e2df;padding:8px}.meta b{color:#60716c}table{width:100%;border-collapse:collapse;margin-top:12px}th{background:#075c50;color:white;padding:12px;text-align:right}td{padding:13px;border-bottom:1px solid #d9e2df}tfoot td{font-weight:bold;font-size:16px}.notes{margin-top:28px;padding:15px;background:#f7f9f8;border-right:4px solid #075c50}.footer{margin-top:70px;display:flex;justify-content:space-between;color:#687873;font-size:11px}</style></head><body><header><div><h1>إيصال حوالة مالية</h1><div>${escapePrint(transfer.direction === 'SENT' ? 'حوالة مرسلة' : 'حوالة مستلمة')}</div></div><div class="brand"><strong>AIS COMPANY</strong><span>النظام المالي المتكامل</span></div></header><div class="meta"><div><b>رقم الحوالة</b><span>${escapePrint(transfer.businessNumber)}</span></div><div><b>التاريخ</b><span>${escapePrint(date)}</span></div><div><b>الجهة</b><span>${escapePrint(transfer.party.name)}</span></div><div><b>العملة</b><span>${escapePrint(transfer.currency)}</span></div></div><h2>تفاصيل العملية</h2><table><thead><tr><th>البيان</th><th>القيمة</th></tr></thead><tbody><tr><td>المبلغ</td><td>${escapePrint(transfer.amount ?? transfer.total)}</td></tr><tr><td>العمولة</td><td>${escapePrint(transfer.commission ?? '0.00')}</td></tr><tr><td>الإجمالي</td><td>${escapePrint(transfer.total)}</td></tr><tr><td>اسم المرسل</td><td>${escapePrint(transfer.senderName)}</td></tr><tr><td>اسم المستفيد</td><td>${escapePrint(transfer.beneficiaryName ?? transfer.recipientName)}</td></tr></tbody><tfoot><tr><td>الإجمالي النهائي</td><td>${escapePrint(transfer.total)} ${escapePrint(transfer.currency)}</td></tr></tfoot></table>${transfer.notes ? `<div class="notes"><b>ملاحظات:</b> ${escapePrint(transfer.notes)}</div>` : ''}<div class="footer"><span>تم إنشاء المستند من AIS Company</span><span>توقيع المسؤول: __________________</span></div></body></html>`)
    printWindow.document.close()
    printWindow.focus()
    window.setTimeout(() => printWindow.print(), 100)
  } catch { printWindow.close(); window.alert('تعذر تحميل بيانات الحوالة للطباعة.') }
}
function App() {
  const [screen, setScreen] = useState<Screen>('dashboard')
  const [mobileNav, setMobileNav] = useState(false)
  const [user, setUser] = useState<ApiUser | null>(null)
  const [authLoading, setAuthLoading] = useState(true)
  useEffect(() => { api<{ user: ApiUser }>('/auth/me').then((result) => setUser(result.user)).catch(() => setUser(null)).finally(() => setAuthLoading(false)); const sync = () => void flushMutations(clientRuntime.apiBaseUrl); window.addEventListener('online', sync); if (navigator.onLine) sync(); return () => window.removeEventListener('online', sync) }, [])
  useEffect(() => { const handleHeaderActions = (event: Event) => { const target = event.target as HTMLElement; if (target.closest('button[aria-label="البحث"]')) setScreen('transfers'); if (target.closest('button[aria-label="الإشعارات"]')) window.alert('لا توجد إشعارات جديدة حالياً.') }; document.addEventListener('click', handleHeaderActions); return () => document.removeEventListener('click', handleHeaderActions) }, [])
  if (authLoading) return <div className="auth-state">جارٍ تحميل النظام...</div>
  if (!user) return <Login onLogin={setUser}/>
  const title = navItems.find((item) => item.id === screen)?.label ?? 'الرئيسية'
  return <div className="app-shell">
    <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <aside className={`sidebar glass-panel ${mobileNav ? 'mobile-open' : ''}`}>
      <div className="brand"><div className="brand-mark">AIS</div><div><strong>AIS COMPANY</strong><span>النظام المالي المتكامل</span></div><button type="button" aria-label="إغلاق قائمة التنقل" className="mobile-close" onClick={() => setMobileNav(false)}><Icon name="close" size={18}/></button></div>
      <div className="workspace-switcher"><div className="company-avatar"><Icon name="building" size={18}/></div><div><small>مساحة العمل</small><strong>AIS Company</strong></div><Icon name="chevron" size={16}/></div>
      <nav>{navItems.map((item) => <button key={item.id} className={screen === item.id ? 'active' : ''} onClick={() => { setScreen(item.id); setMobileNav(false) }}><Icon name={item.icon}/><span>{item.label}</span>{item.id === 'transfers' && <em>12</em>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="sync-status"><i/><div><strong>متصل الآن</strong><span>تمت المزامنة منذ لحظات</span></div></div><button type="button" className="profile" onClick={() => setScreen('settings')}><span className="avatar">{user.username[0]}</span><span><strong>{user.username}</strong><small>{user.role === 'ADMIN' ? 'المدير العام' : 'مستخدم للعرض'}</small></span><Icon name="settings" size={17}/></button></div>
    </aside>
    <main className="main-area">
      <header className="top-header"><button type="button" aria-label="فتح قائمة التنقل" className="mobile-menu" onClick={() => setMobileNav(true)}><Icon name="menu"/></button><div className="breadcrumb"><span>مساحة العمل</span><b>/</b><strong>{title}</strong></div><div className="header-actions"><button type="button" aria-label="البحث" className="icon-button"><Icon name="search"/></button><button type="button" aria-label="الإشعارات" className="icon-button notification"><Icon name="bell"/><i/></button><span className="header-divider"/><span className="header-date">الأحد، 16 أغسطس 2026</span></div></header>
      <div className="page-content">{screen === 'dashboard' && <Dashboard user={user} onNavigate={setScreen}/>} {screen === 'transfers' && <TransfersV2 canManage={user.role === 'ADMIN'}/>} {screen === 'settlements' && <SettlementsByRole canManage={user.role === 'ADMIN'}/>} {screen === 'accounts' && <AccountsByRole canManage={user.role === 'ADMIN'}/>} {screen === 'people' && <PeopleV2 canManage={user.role === 'ADMIN'}/>} {screen === 'reports' && <Reports/>} {screen === 'settings' && <SettingsV2 user={user} onLogout={() => { fetch(`${clientRuntime.apiBaseUrl}/auth/logout`, { method: 'POST', credentials: 'include' }).finally(() => window.location.reload()) }}/>}</div>
    </main>
    <div className="mobile-tabbar glass-panel">{navItems.slice(0, 5).map((item) => <button key={item.id} className={screen === item.id ? 'active' : ''} onClick={() => setScreen(item.id)}><Icon name={item.icon} size={19}/><span>{item.label}</span></button>)}</div>
  </div>
}

function Login({ onLogin }: { onLogin: (user: ApiUser) => void }) {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('')
    try { const result = await api<{ user: ApiUser }>('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) }); onLogin(result.user) } catch { setError('بيانات الدخول غير صحيحة.') } finally { setBusy(false) }
  }
  return <div className="auth-state"><form className="auth-card glass-card" onSubmit={submit} dir="rtl"><div className="brand-mark">AIS</div><span className="eyebrow">AIS COMPANY</span><h1>تسجيل الدخول</h1><p>ادخل إلى مساحة العمل المالية الآمنة.</p><label>اسم المستخدم<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" required/></label><label>كلمة المرور<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" required/></label>{error && <div className="form-error">{error}</div>}<GlassButton type="submit" primary>{busy ? 'جارٍ التحقق...' : 'دخول'}</GlassButton></form></div>
}

function PageHeader({ eyebrow, title, description, action, onAction }: { eyebrow: string; title: string; description: string; action?: string; onAction?: () => void }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action && onAction && <GlassButton primary onClick={onAction}><Icon name="plus" size={18}/>{action}</GlassButton>}</div> }
function Dashboard({ user, onNavigate }: { user: ApiUser; onNavigate: (s: Screen) => void }) {
  const [data, setData] = useState<DashboardData | null>(null)
  const [recent, setRecent] = useState<UiTransfer[]>([])
  useEffect(() => { Promise.all([api<DashboardData>('/reports/dashboard'), api<ApiTransfer[]>('/transfers')]).then(([summary, transfers]) => { setData(summary); setRecent(transfers.slice(0, 3).map(toUiTransfer)) }).catch(() => { setData({ transferCount: 0, settlementCount: 0, balances: [], byCurrency: [] }) }) }, [])
  return <><PageHeader eyebrow="نظرة عامة" title={`مرحباً، ${user.username}`} description="إليك ملخص العمليات المالية الفعلية لمساحة العمل." action="حوالة جديدة" onAction={() => onNavigate('transfers')}/><section className="hero-balance glass-card"><div className="balance-copy"><span>الأرصدة الحالية حسب العملة</span><div className="balance-currency-list">{data?.balances.length ? data.balances.map((item) => <div className="balance-currency-row" key={item.currency}><strong>{item.currency}</strong><span><b>نطلبه</b> {item.weAreOwed}</span><span><b>يطلبنا</b> {item.theyAreOwed}</span></div>) : <p className="empty-copy">لا توجد أرصدة مسجلة بعد.</p>}</div><small>من بيانات PostgreSQL الحالية</small></div><div className="balance-orbit"><span>العملات</span><strong>{data?.balances.length ?? 0}</strong></div><div className="balance-footer"><span>تم التحديث من الخادم</span><button onClick={() => onNavigate('accounts')}>عرض تفاصيل الأرصدة <Icon name="arrow" size={16}/></button></div></section><div className="stats-grid"><StatCard label="الحوالات" value={String(data?.transferCount ?? 0)} detail="ضمن الفترة الحالية" icon="transfer"/><StatCard label="التسويات" value={String(data?.settlementCount ?? 0)} detail="ضمن الفترة الحالية" icon="settle"/><StatCard label="عملات نشطة" value={String(data?.balances.length ?? 0)} detail="بدون جمع بينها" icon="account"/><StatCard label="العمولات" value={data?.byCurrency[0]?.commission ?? '0.00'} detail={data?.byCurrency[0]?.currency ?? '—'} icon="arrow"/></div><div className="dashboard-grid"><GlassCard className="recent-card"><div className="card-head"><div><span className="eyebrow">النشاط الأخير</span><h2>آخر الحوالات</h2></div><button onClick={() => onNavigate('transfers')}>عرض الكل <Icon name="arrow" size={15}/></button></div><div className="activity-list">{recent.length ? recent.map((t) => <Activity key={t.no} transfer={t}/>) : <p className="empty-copy">لا توجد حوالات مسجلة بعد.</p>}</div></GlassCard><GlassCard className="currency-card"><div className="card-head"><div><span className="eyebrow">التوزيع المالي</span><h2>الأرصدة حسب العملة</h2></div></div>{data?.balances.length ? data.balances.map((item) => <Currency key={item.currency} name={item.currency} amount={item.weAreOwed} percent="100%"/>) : <p className="empty-copy">لا توجد أرصدة مسجلة بعد.</p>}</GlassCard></div></> }
function StatCard({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: IconName }) { return <GlassCard className="stat-card"><div className="stat-icon"><Icon name={icon} size={19}/></div><span>{label}</span><strong>{value}</strong><small>{detail}</small></GlassCard> }
function Activity({ transfer: t }: { transfer: UiTransfer }) { return <div className="activity-row"><div className="activity-icon"><Icon name={t.type.includes('إرسال') ? 'arrow' : 'transfer'} size={18}/></div><div className="activity-main"><strong>{t.person}</strong><span>{t.no} · {t.date}</span></div><div className="activity-amount"><strong>{t.amount}</strong><span className={t.status === 'مكتملة' ? 'success' : 'warning'}>{t.status}</span></div></div> }
function Currency({ name, amount, percent }: { name: string; amount: string; percent: string }) { return <div className="currency-row"><div className="currency-symbol">{name[0]}</div><div className="currency-main"><strong>{name}</strong><span>{amount}</span><div className="progress"><i style={{ width: percent }}/></div></div><small>{percent}</small></div> }
function TransfersV2({ canManage }: { canManage: boolean }) {
  const [rows, setRows] = useState<ApiTransfer[]>([])
  const [loading, setLoading] = useState(true)
  const [formOpen, setFormOpen] = useState(false)
  const [selected, setSelected] = useState<ApiTransfer | null>(null)
  const reload = () => { setLoading(true); api<ApiTransfer[]>('/transfers').then(setRows).catch(() => setRows([])).finally(() => setLoading(false)) }
  useEffect(reload, [])
  return <><PageHeader eyebrow="العمليات المالية" title="الحوالات" description="تابع وأدر الحوالات المحفوظة في PostgreSQL." action={canManage ? 'حوالة جديدة' : undefined} onAction={() => setFormOpen(true)}/><GlassCard className="table-card"><div className="table-top"><div><h2>كل الحوالات</h2><span>{loading ? 'جارٍ التحميل...' : `${rows.length} عملية مسجلة`}</span></div></div><div className="table-wrap"><table><thead><tr><th>رقم الحوالة</th><th>الشخص / الجهة</th><th>النوع</th><th>العملة</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th><th>الإجراءات</th></tr></thead><tbody>{rows.map((t) => <tr key={t.id}><td><strong className="mono">{t.businessNumber}</strong></td><td><div className="person-cell"><span>{t.party.name[0]}</span><strong>{t.party.name}</strong></div></td><td>{t.direction === 'SENT' ? 'إرسال حوالة' : 'استلام حوالة'}</td><td><b className="currency-code">{t.currency}</b></td><td><strong dir="ltr">{t.total}</strong></td><td><span className="status success"><i/>مسجلة</span></td><td>{new Date(t.date).toLocaleDateString('ar-IQ')}</td><td><button type="button" aria-label={`إجراءات الحوالة ${t.businessNumber}`} className="more-button" onClick={() => setSelected(t)}><Icon name="more" size={18}/></button></td></tr>)}</tbody></table>{!loading && !rows.length && <p className="empty-copy">لا توجد حوالات محفوظة حالياً.</p>}</div></GlassCard>{formOpen && <TransferForm onClose={() => setFormOpen(false)} onSaved={() => { setFormOpen(false); reload() }}/>} {selected && <TransferActionMenu transfer={selected} canManage={canManage} onClose={() => setSelected(null)} onChanged={() => { setSelected(null); reload() }}/>}</>
}

function TransferActionMenu({ transfer, canManage, onClose, onChanged }: { transfer: ApiTransfer; canManage: boolean; onClose: () => void; onChanged: () => void }) {
  const [view, setView] = useState(false)
  const [edit, setEdit] = useState(false)
  async function remove() { if (!window.confirm('هل تريد حذف هذه الحوالة؟')) return; await api(`/transfers/${transfer.id}`, { method: 'DELETE' }); onChanged() }
  return <><Modal title={`إجراءات الحوالة ${transfer.businessNumber}`} onClose={onClose}><div className="action-list"><GlassButton onClick={() => setView(true)}><Icon name="building" size={17}/>عرض الحوالة</GlassButton><GlassButton onClick={() => { const printWindow = window.open('', '_blank', 'width=900,height=1100'); if (printWindow) void printTransfer(transfer.id, printWindow); else window.alert('اسمح بالنوافذ المنبثقة للطباعة ثم أعد المحاولة.') }}><Icon name="printer" size={17}/>طباعة الحوالة</GlassButton>{canManage && <><GlassButton onClick={() => setEdit(true)}><Icon name="settings" size={17}/>تعديل الحوالة</GlassButton><GlassButton onClick={() => void remove()} className="danger-button"><Icon name="close" size={17}/>حذف الحوالة</GlassButton></>}</div></Modal>{view && <Modal title="تفاصيل الحوالة" onClose={() => setView(false)}><div className="detail-list"><p><b>رقم الحوالة</b><span>{transfer.businessNumber}</span></p><p><b>الجهة</b><span>{transfer.party.name}</span></p><p><b>الاتجاه</b><span>{transfer.direction === 'SENT' ? 'حوالة مرسلة' : 'حوالة مستلمة'}</span></p><p><b>التاريخ</b><span>{new Date(transfer.date).toLocaleDateString('ar-IQ')}</span></p><p><b>المبلغ</b><span>{transfer.amount} {transfer.currency}</span></p><p><b>العمولة</b><span>{transfer.commission} {transfer.currency}</span></p><p><b>الإجمالي</b><span>{transfer.total} {transfer.currency}</span></p><p><b>اسم المرسل</b><span>{transfer.senderName}</span></p><p><b>اسم المستفيد</b><span>{transfer.beneficiaryName ?? transfer.recipientName ?? '—'}</span></p></div></Modal>}{edit && <TransferEditForm transfer={transfer} onClose={() => setEdit(false)} onSaved={onChanged}/>}</>
}

function TransferEditForm({ transfer, onClose, onSaved }: { transfer: ApiTransfer; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ partyId: transfer.party.id, direction: transfer.direction, date: new Date(transfer.date).toISOString().slice(0, 10), senderName: transfer.senderName ?? '', recipientName: transfer.recipientName ?? '', location: transfer.location ?? '', beneficiaryName: transfer.beneficiaryName ?? '', beneficiaryPhone: transfer.beneficiaryPhone ?? '', beneficiaryCountry: transfer.beneficiaryCountry ?? '', currency: transfer.currency, amount: transfer.amount ?? '', commission: transfer.commission ?? '0', notes: transfer.notes ?? '' })
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api(`/transfers/${transfer.id}`, { method: 'PATCH', body: JSON.stringify(form) }); onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تعديل الحوالة.') } finally { setBusy(false) } }
  return <Modal title="تعديل الحوالة" onClose={onClose}><form onSubmit={submit} className="form-grid"><FormField label="الاتجاه"><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value as ApiTransfer['direction'] })}><option value="SENT">حوالة مرسلة</option><option value="RECEIVED">حوالة مستلمة</option></select></FormField><FormField label="التاريخ"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} required/></FormField><FormField label="اسم المرسل"><input value={form.senderName} onChange={(e) => setForm({ ...form, senderName: e.target.value })} required/></FormField><FormField label="اسم المستفيد"><input value={form.beneficiaryName} onChange={(e) => setForm({ ...form, beneficiaryName: e.target.value })}/></FormField><FormField label="المبلغ"><input inputMode="decimal" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required/></FormField><FormField label="العمولة"><input inputMode="decimal" value={form.commission} onChange={(e) => setForm({ ...form, commission: e.target.value })} required/></FormField>{error && <div className="form-error">{error}</div>}<FormActions busy={busy} onClose={onClose}/></form></Modal>
}
function Accounts() { const [rows, setRows] = useState<Array<{ partyId: string; partyName: string; partyType: string; currency: string; weAreOwed: string; theyAreOwed: string }>>([]); useEffect(() => { api<typeof rows>('/accounts').then(setRows).catch(() => setRows([])) }, []); return <><PageHeader eyebrow="الذمم والأرصدة" title="الحسابات" description="أرصدة فعلية مشتقة من PostgreSQL حسب الجهة والعملة."/><div className="accounts-layout"><GlassCard className="accounts-list"><div className="card-head"><div><span className="eyebrow">دليل الحسابات</span><h2>كل الحسابات</h2></div></div>{rows.map((row) => <div className="account-row" key={`${row.partyId}-${row.currency}`}><span className="person-avatar">{row.partyName[0]}</span><div><strong>{row.partyName}</strong><small>{row.partyType} · {row.currency}</small></div><Icon name="chevron" size={16}/></div>)}{!rows.length && <p className="empty-copy">لا توجد أرصدة مسجلة بعد.</p>}</GlassCard><GlassCard className="account-detail"><div className="detail-top"><div><span className="eyebrow">الأرصدة الحالية</span><h2>حسب العملة</h2><span className="muted">لا يتم جمع العملات المختلفة</span></div></div>{rows.slice(0, 4).map((row) => <div className="account-balance-grid" key={`${row.partyId}-detail-${row.currency}`}><div><span>{row.currency} · نطلبه</span><strong>{row.weAreOwed}</strong><small>{row.partyName}</small></div><div><span>{row.currency} · يطلبنا</span><strong>{row.theyAreOwed}</strong><small>{row.partyName}</small></div></div>)}{!rows.length && <p className="empty-copy">ستظهر تفاصيل الحساب بعد تسجيل عمليات فعلية.</p>}</GlassCard></div></> }
function AccountsByRole({ canManage }: { canManage: boolean }) { return canManage ? <AccountsWithOpening/> : <Accounts/> }
function AccountsWithOpening() { return <><Accounts/><OpeningBalances/></> }
function OpeningBalances() { const [rows, setRows] = useState<ApiOpeningBalance[]>([]); const [parties, setParties] = useState<ApiParty[]>([]); const [formOpen, setFormOpen] = useState(false); const reload = () => api<ApiOpeningBalance[]>('/opening-balances').then(setRows).catch(() => setRows([])); useEffect(() => { reload(); api<ApiParty[]>('/parties').then(setParties).catch(() => setParties([])) }, []); return <GlassCard className="table-card opening-balances-card"><div className="card-head"><div><span className="eyebrow">تهيئة الحسابات</span><h2>الأرصدة الافتتاحية</h2><p className="muted">القيم التي يبدأ منها احتساب رصيد كل جهة وعملة.</p></div><GlassButton primary onClick={() => setFormOpen(true)}><Icon name="plus" size={17}/>إضافة رصيد</GlassButton></div><div className="table-wrap"><table><thead><tr><th>الجهة</th><th>العملة</th><th>الاتجاه</th><th>المبلغ</th><th/></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.party.name}</td><td><b className="currency-code">{row.currency}</b></td><td>{row.direction === 'WE_ARE_OWED' ? 'مستحق لنا' : 'مستحق علينا'}</td><td dir="ltr">{row.amount}</td><td><button className="more-button" onClick={() => { if (window.confirm('حذف هذا الرصيد الافتتاحي؟')) api(`/opening-balances/${row.id}`, { method: 'DELETE' }).then(reload) }}><Icon name="close" size={17}/></button></td></tr>)}</tbody></table>{!rows.length && <p className="empty-copy">لا توجد أرصدة افتتاحية مسجلة.</p>}</div>{formOpen && <OpeningBalanceForm parties={parties} onClose={() => setFormOpen(false)} onSaved={() => { setFormOpen(false); reload() }}/>}</GlassCard> }
function OpeningBalanceForm({ parties, onClose, onSaved }: { parties: ApiParty[]; onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ partyId: '', currency: 'USD', direction: 'WE_ARE_OWED', amount: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api('/opening-balances', { method: 'POST', body: JSON.stringify(form) }); onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'تعذر حفظ الرصيد.') } finally { setBusy(false) } } return <Modal title="إضافة رصيد افتتاحي" onClose={onClose}><form onSubmit={submit} className="form-grid"><FormField label="الجهة"><PartySelect value={form.partyId} parties={parties} onChange={(partyId) => setForm({ ...form, partyId })}/></FormField><FormField label="العملة"><select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })}><option>USD</option><option>IQD</option><option>IRR_TOMAN</option><option>EUR</option><option>SAR</option></select></FormField><FormField label="الاتجاه"><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })}><option value="WE_ARE_OWED">مستحق لنا</option><option value="THEY_ARE_OWED">مستحق علينا</option></select></FormField><FormField label="المبلغ"><input inputMode="decimal" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required/></FormField>{error && <div className="form-error">{error}</div>}<FormActions busy={busy} onClose={onClose}/></form></Modal> }
function PeopleV2({ canManage }: { canManage: boolean }) {
  const [rows, setRows] = useState<ApiParty[]>([]); const [loading, setLoading] = useState(true); const [formOpen, setFormOpen] = useState(false); const [selected, setSelected] = useState<ApiParty | null>(null)
  const reload = () => { setLoading(true); api<ApiParty[]>('/parties').then(setRows).catch(() => setRows([])).finally(() => setLoading(false)) }; useEffect(reload, [])
  return <><PageHeader eyebrow="دليل الجهات" title="الأشخاص والجهات" description="الجهات المحفوظة فعلياً في PostgreSQL." action={canManage ? 'إضافة جهة' : undefined} onAction={() => setFormOpen(true)}/><GlassCard className="table-card"><div className="table-top"><div><h2>كل الجهات</h2><span>{loading ? 'جارٍ التحميل...' : `${rows.length} جهة`}</span></div></div><div className="table-wrap"><table><thead><tr><th>الاسم</th><th>النوع</th><th>الهاتف</th><th>البلد</th><th>الإجراءات</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="person-cell"><span>{row.name[0]}</span><strong>{row.name}</strong></div></td><td>{row.type === 'PERSON' ? 'شخص' : row.type === 'OFFICE' ? 'مكتب' : 'شركة'}</td><td>{row.phone ?? '—'}</td><td>{row.country ?? '—'}</td><td><button type="button" aria-label={`إجراءات الجهة ${row.name}`} className="more-button" onClick={() => setSelected(row)}><Icon name="more" size={18}/></button></td></tr>)}</tbody></table>{!loading && !rows.length && <p className="empty-copy">لا توجد جهات محفوظة حالياً.</p>}</div></GlassCard>{formOpen && <PartyForm onClose={() => setFormOpen(false)} onSaved={() => { setFormOpen(false); reload() }}/>} {selected && <PartyActionMenu party={selected} canManage={canManage} onClose={() => setSelected(null)} onChanged={() => { setSelected(null); reload() }}/>}</>
}

function PartyActionMenu({ party, canManage, onClose, onChanged }: { party: ApiParty; canManage: boolean; onClose: () => void; onChanged: () => void }) {
  const [view, setView] = useState(false); const [edit, setEdit] = useState(false)
  async function remove() { if (!window.confirm('هل تريد حذف هذه الجهة؟')) return; await api(`/parties/${party.id}`, { method: 'DELETE' }); onChanged() }
  return <><Modal title={`إجراءات الجهة: ${party.name}`} onClose={onClose}><div className="action-list"><GlassButton onClick={() => setView(true)}><Icon name="people" size={17}/>عرض بيانات الجهة</GlassButton>{canManage && <><GlassButton onClick={() => setEdit(true)}><Icon name="settings" size={17}/>تعديل الجهة</GlassButton><GlassButton onClick={() => void remove()} className="danger-button"><Icon name="close" size={17}/>حذف الجهة</GlassButton></>}</div></Modal>{view && <Modal title="بيانات الجهة" onClose={() => setView(false)}><div className="detail-list"><p><b>الاسم</b><span>{party.name}</span></p><p><b>النوع</b><span>{party.type === 'PERSON' ? 'شخص' : party.type === 'OFFICE' ? 'مكتب' : 'شركة'}</span></p><p><b>الهاتف</b><span>{party.phone ?? '—'}</span></p><p><b>العنوان</b><span>{party.address ?? '—'}</span></p><p><b>البلد</b><span>{party.country ?? '—'}</span></p><p><b>ملاحظات</b><span>{party.notes ?? '—'}</span></p></div></Modal>}{edit && <PartyEditForm party={party} onClose={() => setEdit(false)} onSaved={onChanged}/>}</>
}

function PartyEditForm({ party, onClose, onSaved }: { party: ApiParty; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ type: party.type, name: party.name, phone: party.phone ?? '', address: party.address ?? '', country: party.country ?? '', notes: party.notes ?? '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api(`/parties/${party.id}`, { method: 'PATCH', body: JSON.stringify(form) }); onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تعديل الجهة.') } finally { setBusy(false) } }
  return <Modal title="تعديل الجهة" onClose={onClose}><form onSubmit={submit} className="form-grid"><FormField label="نوع الجهة"><select value={form.type} disabled><option value="PERSON">شخص</option><option value="OFFICE">مكتب</option><option value="COMPANY">شركة</option></select></FormField><FormField label="الاسم"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required/></FormField><FormField label="الهاتف"><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/></FormField><FormField label="العنوان"><input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })}/></FormField><FormField label="البلد"><input value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })}/></FormField><FormField label="ملاحظات"><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></FormField>{error && <div className="form-error">{error}</div>}<FormActions busy={busy} onClose={onClose}/></form></Modal>
}
function SettlementsByRole({ canManage }: { canManage: boolean }) { return canManage ? <Settlements/> : <SettlementsReadOnly/> }
function SettlementsReadOnly() { const [rows, setRows] = useState<ApiSettlement[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { api<ApiSettlement[]>('/settlements').then(setRows).catch(() => setRows([])).finally(() => setLoading(false)) }, []); return <><PageHeader eyebrow="العمليات المالية" title="التسويات" description="التسويات المسجلة فعلياً في PostgreSQL."/><GlassCard className="table-card"><div className="table-top"><div><h2>كل التسويات</h2><span>{loading ? 'جارٍ التحميل...' : `${rows.length} تسوية`}</span></div></div><div className="table-wrap"><table><thead><tr><th>رقم التسوية</th><th>الجهة</th><th>الاتجاه</th><th>العملة</th><th>المبلغ</th><th>التاريخ</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong className="mono">{row.businessNumber}</strong></td><td>{row.party.name}</td><td>{row.direction === 'THEY_PAID_US' ? 'هم دفعوا لنا' : 'نحن دفعنا لهم'}</td><td><b className="currency-code">{row.currency}</b></td><td dir="ltr">{row.amount}</td><td>{new Date(row.date).toLocaleDateString('ar-IQ')}</td></tr>)}</tbody></table>{!loading && !rows.length && <p className="empty-copy">لا توجد تسويات محفوظة حالياً.</p>}</div></GlassCard></> }

function Settlements() { const [rows, setRows] = useState<ApiSettlement[]>([]); const [loading, setLoading] = useState(true); const [formOpen, setFormOpen] = useState(false); const reload = () => { setLoading(true); api<ApiSettlement[]>('/settlements').then(setRows).finally(() => setLoading(false)) }; useEffect(reload, []); return <><PageHeader eyebrow="العمليات المالية" title="التسويات" description="التسويات المسجلة فعلياً في PostgreSQL." action="إضافة تسوية"/><div className="page-action"><GlassButton primary onClick={() => setFormOpen(true)}><Icon name="plus" size={17}/>إضافة تسوية</GlassButton></div><GlassCard className="table-card"><div className="table-top"><div><h2>كل التسويات</h2><span>{loading ? 'جارٍ التحميل...' : `${rows.length} تسوية`}</span></div></div><div className="table-wrap"><table><thead><tr><th>رقم التسوية</th><th>الجهة</th><th>الاتجاه</th><th>العملة</th><th>المبلغ</th><th>التاريخ</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong className="mono">{row.businessNumber}</strong></td><td>{row.party.name}</td><td>{row.direction === 'THEY_PAID_US' ? 'هم دفعوا لنا' : 'نحن دفعنا لهم'}</td><td><b className="currency-code">{row.currency}</b></td><td dir="ltr">{row.amount}</td><td>{new Date(row.date).toLocaleDateString('ar-IQ')}</td></tr>)}</tbody></table>{!loading && !rows.length && <p className="empty-copy">لا توجد تسويات محفوظة حالياً.</p>}</div></GlassCard>{formOpen && <SettlementForm onClose={() => setFormOpen(false)} onSaved={() => { setFormOpen(false); reload() }}/>}</> }
function Reports() { const [data, setData] = useState<DashboardData | null>(null); useEffect(() => { api<DashboardData>('/reports/dashboard').then(setData).catch(() => setData(null)) }, []); return <><PageHeader eyebrow="التحليل المالي" title="التقارير" description="ملخصات مشتقة من العمليات الفعلية، مع عزل العملات."/><div className="stats-grid"><StatCard label="الحوالات" value={String(data?.transferCount ?? 0)} detail="كل الفترات" icon="transfer"/><StatCard label="التسويات" value={String(data?.settlementCount ?? 0)} detail="كل الفترات" icon="settle"/><StatCard label="العملات" value={String(data?.balances.length ?? 0)} detail="مستقلة" icon="account"/><StatCard label="العمولة" value={data?.byCurrency[0]?.commission ?? '0.00'} detail={data?.byCurrency[0]?.currency ?? '—'} icon="arrow"/></div><GlassCard className="table-card"><div className="card-head"><div><span className="eyebrow">الأرصدة الحالية</span><h2>حسب العملة</h2></div></div><div className="activity-list">{data?.balances.map((row) => <div className="activity-row" key={`${row.currency}-${row.weAreOwed}`}><div className="currency-symbol">{row.currency[0]}</div><div className="activity-main"><strong>{row.currency}</strong><span>الأرصدة مستقلة ولا يتم تحويلها</span></div><div className="activity-amount"><strong>{row.weAreOwed}</strong><span>نطلبه</span></div></div>)}</div>{!data?.balances.length && <p className="empty-copy">لا توجد بيانات تقارير بعد.</p>}</GlassCard></> }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop"><section className="modal-card glass-card" dir="rtl"><div className="modal-head"><h2>{title}</h2><button type="button" className="icon-button" onClick={onClose}><Icon name="close" size={18}/></button></div>{children}</section></div> }
function FormField({ label, children }: { label: string; children: ReactNode }) { return <label className="form-field"><span>{label}</span>{children}</label> }
function FormActions({ busy, onClose }: { busy: boolean; onClose: () => void }) { return <div className="form-actions"><GlassButton type="button" onClick={onClose}>إلغاء</GlassButton><GlassButton type="submit" primary>{busy ? 'جارٍ الحفظ...' : 'حفظ'}</GlassButton></div> }
function PartyForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ type: 'PERSON', name: '', phone: '', country: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api('/parties', { method: 'POST', body: JSON.stringify(form) }); onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'تعذر حفظ الجهة.') } finally { setBusy(false) } } return <Modal title="إضافة جهة" onClose={onClose}><form onSubmit={submit} className="form-grid"><FormField label="نوع الجهة"><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="PERSON">شخص</option><option value="OFFICE">مكتب</option><option value="COMPANY">شركة</option></select></FormField><FormField label="الاسم"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required/></FormField><FormField label="الهاتف"><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/></FormField><FormField label="البلد"><input value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })}/></FormField>{error && <div className="form-error">{error}</div>}<FormActions busy={busy} onClose={onClose}/></form></Modal> }
function PartySelect({ value, onChange, parties }: { value: string; onChange: (value: string) => void; parties: ApiParty[] }) { return <select value={value} onChange={(e) => onChange(e.target.value)} required><option value="">اختر الجهة</option>{parties.map((party) => <option key={party.id} value={party.id}>{party.name}</option>)}</select> }
function TransferForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [parties, setParties] = useState<ApiParty[]>([]); const [form, setForm] = useState({ partyId: '', direction: 'SENT', date: new Date().toISOString().slice(0, 10), senderName: '', currency: 'USD', amount: '', commission: '0' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { api<ApiParty[]>('/parties').then(setParties).catch(() => setError('تعذر تحميل الجهات.')) }, []); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api('/transfers', { method: 'POST', body: JSON.stringify(form) }); onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'تعذر حفظ الحوالة.') } finally { setBusy(false) } } return <Modal title="إضافة حوالة" onClose={onClose}><form onSubmit={submit} className="form-grid"><FormField label="الجهة"><PartySelect value={form.partyId} parties={parties} onChange={(partyId) => setForm({ ...form, partyId })}/></FormField><FormField label="الاتجاه"><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })}><option value="SENT">حوالة مرسلة</option><option value="RECEIVED">حوالة مستلمة</option></select></FormField><FormField label="التاريخ"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} required/></FormField><FormField label="اسم المرسل"><input value={form.senderName} onChange={(e) => setForm({ ...form, senderName: e.target.value })} required/></FormField><FormField label="العملة"><select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })}><option>USD</option><option>IQD</option><option>IRR_TOMAN</option><option>EUR</option><option>SAR</option></select></FormField><FormField label="المبلغ"><input inputMode="decimal" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required/></FormField><FormField label="العمولة"><input inputMode="decimal" value={form.commission} onChange={(e) => setForm({ ...form, commission: e.target.value })} required/></FormField>{error && <div className="form-error">{error}</div>}<FormActions busy={busy} onClose={onClose}/></form></Modal> }
function SettlementForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [parties, setParties] = useState<ApiParty[]>([]); const [form, setForm] = useState({ partyId: '', direction: 'THEY_PAID_US', date: new Date().toISOString().slice(0, 10), currency: 'USD', amount: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { api<ApiParty[]>('/parties').then(setParties).catch(() => setError('تعذر تحميل الجهات.')) }, []); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api('/settlements', { method: 'POST', body: JSON.stringify(form) }); onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'تعذر حفظ التسوية.') } finally { setBusy(false) } } return <Modal title="إضافة تسوية" onClose={onClose}><form onSubmit={submit} className="form-grid"><FormField label="الجهة"><PartySelect value={form.partyId} parties={parties} onChange={(partyId) => setForm({ ...form, partyId })}/></FormField><FormField label="الاتجاه"><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })}><option value="THEY_PAID_US">هم دفعوا لنا</option><option value="WE_PAID_THEM">نحن دفعنا لهم</option></select></FormField><FormField label="التاريخ"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} required/></FormField><FormField label="العملة"><select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })}><option>USD</option><option>IQD</option><option>IRR_TOMAN</option><option>EUR</option><option>SAR</option></select></FormField><FormField label="المبلغ"><input inputMode="decimal" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required/></FormField>{error && <div className="form-error">{error}</div>}<FormActions busy={busy} onClose={onClose}/></form></Modal> }
function SettingsV2({ user, onLogout }: { user: ApiUser; onLogout: () => void }) { return <><PageHeader eyebrow="النظام" title="الإعدادات" description="بيانات الشركة التي تظهر في مستندات الحوالات والفواتير وإدارة الجلسة الحالية."/><div className="settings-grid"><GlassCard className="company-settings-card"><div className="settings-card-head"><div><span className="eyebrow">هوية الشركة</span><h2>AIS COMPANY</h2></div><img src="/icons/ais-192.svg" alt="شعار AIS Company" className="company-logo"/></div><div className="settings-info-list"><p><b>الاسم العربي</b><span>الشركة العامة للاستيراد والتصدير</span></p><p><b>الاسم الإنكليزي</b><span>General Company for Import &amp; Export</span></p><p><b>اسم النظام</b><span>AIS COMPANY — النظام المالي المتكامل</span></p><p><b>نوع المستندات</b><span>حوالات مالية وفواتير تجارية</span></p><p><b>اللغة والاتجاه</b><span>العربية — RTL</span></p></div></GlassCard><GlassCard className="document-settings-card"><div className="settings-card-head"><div><span className="eyebrow">مظهر المستند</span><h2>الحوالة والفاتورة</h2></div><div className="company-stamp" aria-label="ختم الشركة">AIS<span>OFFICIAL</span></div></div><div className="settings-info-list"><p><b>الشعار</b><span>يظهر في رأس مستند الحوالة والفاتورة.</span></p><p><b>الختم</b><span>ختم الشركة الرسمي في أسفل المستند.</span></p><p><b>الطباعة</b><span>A4 — تصميم عربي RTL جاهز للطباعة.</span></p><p><b>الحساب الحالي</b><span>{user.username} — {user.role === 'ADMIN' ? 'المدير العام' : 'مستخدم للعرض'}</span></p></div></GlassCard><GlassCard className="session-settings-card"><div className="settings-card-head"><div><span className="eyebrow">الأمان</span><h2>الجلسة الحالية</h2></div><Icon name="settings" size={25}/></div><p className="muted">لا يتم حفظ كلمات المرور في الواجهة. تسجيل الخروج ينهي جلسة هذا الجهاز فقط.</p><GlassButton primary onClick={onLogout}>تسجيل الخروج</GlassButton></GlassCard></div></> }


import { createRoot } from 'react-dom/client'
createRoot(document.getElementById('root')!).render(<App />)
